version: '3'

services:
  payment-processor:
    image: payment-processor
    container_name: payment_processor
    ports:
      - 10010:10010
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml
    networks:
      - p-network
networks:
  p-network: