// Code generated by goctl. DO NOT EDIT.
package asset

type BalanceItem struct {
	CoinID int    `json:"coin_id"`
	Free   string `json:"free"`
	Used   string `json:"used"`
	Total  string `json:"total"`
}

type BalanceReq struct {
	Quote  string `json:"quote,optional" form:"quote,optional"`
	CoinID int    `json:"coin_id,optional" form:"coin_id,optional"`
	UserID int    `json:"user_id,optional" form:"user_id,optional"`
}

type BalanceResp struct {
	Total   string        `json:"total"`
	Quote   string        `json:"quote"`
	Balance []BalanceItem `json:"balance"`
}

type BatchOperateReq struct {
	Data []OperateReq `json:"data"`
}

type ChainListItem struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	Icon   string `json:"icon"`
	Status int    `json:"status"`
	EVM    bool   `json:"evm"`
}

type ChainListReq struct {
	Name     string `json:"name,optional" form:"name,optional"`
	Page     int    `json:"page,optional" form:"page,optional"`
	PageSize int    `json:"page_size,optional" form:"page_size,optional"`
}

type ChainListResp struct {
	PageResp
	Records []ChainListItem `json:"records"`
}

type CoinListItem struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	Icon      string `json:"icon"`
	MinAmount string `json:"min_amount"`
	Precision int32  `json:"precision"`
	Status    int    `json:"status"`
	Desc      string `json:"desc"`
}

type CoinListReq struct {
	Name     string `json:"name,optional" form:"name,optional"`
	Page     int    `json:"page,optional" form:"page,optional"`
	PageSize int    `json:"page_size,optional" form:"page_size,optional"`
}

type CoinListResp struct {
	PageResp
	Records []CoinListItem `json:"records"`
}

type EmptyReq struct {
}

type EmptyResp struct {
}

type HistoryItem struct {
	Time            int    `json:"time"`
	UserID          int    `json:"user_id"`
	CoinID          int    `json:"coin_id"`
	AfterAvailable  string `json:"after_available"`
	AfterFrozen     string `json:"after_frozen"`
	BeforeAvailable string `json:"before_available"`
	BeforeFrozen    string `json:"before_frozen"`
	Volume          string `json:"volume"`
	Method          string `json:"method"`
	Business        string `json:"business"`
	BusinessNo      string `json:"business_no"`
	Data            string `json:"data"`
}

type HistoryReq struct {
	CoinID    int    `json:"coin_id,optional" form:"coin_id,optional"`
	Business  string `json:"business,optional" form:"business,optional"`
	Method    string `json:"method,optional" form:"method,optional"`
	StartTime int    `json:"start_time,optional" form:"start_time,optional"`
	EndTime   int    `json:"end_time,optional" form:"end_time,optional"`
	UserID    int    `json:"user_id,optional" form:"user_id,optional"`
	Page      int    `json:"page,optional" form:"page,optional"`
	PageSize  int    `json:"page_size,optional" form:"page_size,optional"`
}

type HistoryResp struct {
	PageResp
	Records []HistoryItem `json:"records"`
}

type OperateReq struct {
	CoinID     int    `json:"coin_id,optional" form:"coin_id,optional"`
	Method     string `json:"method,optional" form:"method,optional"`
	Volume     string `json:"volume,optional" form:"volume,optional"`
	Business   string `json:"business,optional" form:"business,optional"`
	BusinessNo string `json:"business_no,optional" form:"business_no,optional"`
	Data       string `json:"data,optional" form:"data,optional"`
	UserID     int    `json:"user_id,optional" form:"user_id,optional"`
}

type PageResp struct {
	Count    int `json:"count"`
	Page     int `json:"page"`
	PageSize int `json:"page_size"`
}

type TokenListItem struct {
	ID                 int    `json:"id"`
	CoinID             uint64 `json:"coin_id"`
	ChainID            uint64 `json:"chain_id"`
	MainTokenID        uint64 `json:"main_token_id"`
	MainCoinID         uint64 `json:"main_coin_id"`
	Address            string `json:"address"`
	MinDepositVolume   string `json:"min_deposit_volume"`
	MinWithdrawVolume  string `json:"min_withdraw_volume"`
	Decimal            int    `json:"decimal"`
	RequireMemo        bool   `json:"require_memo"`
	CanDeposit         bool   `json:"can_deposit"`
	CanWithdraw        bool   `json:"can_withdraw"`
	WithdrawConfirmNum int    `json:"withdraw_confirm_num"`
	DepositConfirmNum  int    `json:"deposit_confirm_num"`
	WithdrawFeeRate    string `json:"withdraw_fee_rate"`
	Remark             string `json:"remark"`
	Fee                string `json:"fee"`
	Status             int    `json:"status"`
}

type TokenListReq struct {
	CoinID   int `json:"coin_id,optional" form:"coin_id,optional"`
	ChainID  int `json:"chain_id,optional" form:"chain_id,optional"`
	Page     int `json:"page,optional" form:"page,optional"`
	PageSize int `json:"page_size,optional" form:"page_size,optional"`
}

type TokenListResp struct {
	PageResp
	Records []TokenListItem `json:"records"`
}
