// Code generated by goctl. DO NOT EDIT.
package wallet

type BicycleNotificationReq struct {
	Type        string `json:"type"`
	Address     string `json:"address"`
	Timestamp   int64  `json:"time"`
	Amount      string `json:"amount"`
	Comment     string `json:"comment"`
	TxHash      string `json:"tx_hash"`
	UserQueryID string `json:"user_query_id"` // 用户提现请求id
}

