// Code generated by goctl. DO NOT EDIT.
package wallet

type CreateDepositAddressReq struct {
	CoinID  int `json:"coin_id,optional" form:"coin_id,optional"`
	ChainID int `json:"chain_id,optional" form:"chain_id,optional"`
	UserID  int `json:"user_id,optional" form:"user_id,optional"`
}

type DepositDetailReq struct {
	ID int `json:"id,optional" form:"id,optional"`
}

type DepositDetailResp struct {
}

type DepositRecordItem struct {
	CreatedAt           int    `json:"created_at"`
	ID                  int    `json:"id"`
	UserID              uint64 `json:"user_id"`
	ChainID             uint64 `json:"chain_id"`
	CoinID              uint64 `json:"coin_id"`
	Volume              string `json:"volume"`
	Address             string `json:"address"`
	Memo                string `json:"memo"`
	Hash                string `json:"hash" gorm:"unique"`
	ConfirmedNum        int    `json:"confirmed_num"`
	ConfirmingThreshold int    `json:"confirming_threshold"`
	Status              int    `json:"status"`
}

type DepositRecordResp struct {
	PageResp
	Records []DepositRecordItem `json:"records"`
}

type DepositRecordsReq struct {
	CoinID    int `json:"coin_id,optional" form:"coin_id,optional"`
	ChainID   int `json:"chain_id,optional" form:"chain_id,optional"`
	UserID    int `json:"user_id,optional" form:"user_id,optional"`
	StartTime int `json:"start_time,optional" form:"start_time,optional"`
	EndTime   int `json:"end_time,optional" form:"end_time,optional"`
	Page      int `json:"page,optional" form:"page,optional"`
	PageSize  int `json:"page_size,optional" form:"page_size,optional"`
}

type EmptyReq struct {
}

type EmptyResp struct {
}

type PageResp struct {
	Count    int `json:"count"`
	Page     int `json:"page"`
	PageSize int `json:"page_size"`
}

type UserDepositAddressReq struct {
	CoinID  int `json:"coin_id,optional" form:"coin_id,optional"`
	ChainID int `json:"chain_id,optional" form:"chain_id,optional"`
	UserID  int `json:"user_id,optional" form:"user_id,optional"`
}

type UserDepositAddressResp struct {
	TokenID int    `json:"token_id"`
	Address string `json:"address"`
	Memo    string `json:"memo"`
}

type WithdrawApproveReq struct {
	ID     int `json:"id,optional" form:"id,optional"`
	UserID int `json:"user_id,optional" form:"user_id,optional"`
}

type WithdrawApproveResp struct {
	ID int `json:"id"`
}

type WithdrawDetailReq struct {
	RedID string `json:"req_id,optional" form:"req_id,optional"`
}

type WithdrawDetailResp struct {
}

type WithdrawRecordItem struct {
	CreatedAt           int    `json:"created_at"`
	ID                  int    `json:"id"`
	UserID              uint64 `json:"user_id"`
	ChainID             uint64 `json:"chain_id"`
	CoinID              uint64 `json:"coin_id"`
	Volume              string `json:"volume"`
	Address             string `json:"address"`
	Memo                string `json:"memo"`
	Hash                string `json:"hash" gorm:"unique"`
	ConfirmedNum        int    `json:"confirmed_num"`
	ConfirmingThreshold int    `json:"confirming_threshold"`
	ReqID               string `json:"req_id" gorm:"unique"`
	Fee                 string `json:"fee"`
	WithdrawFee         string `json:"withdraw_fee"`
	RealFee             string `json:"real_fee"`
	RealEstimateFee     string `json:"real_estimate_fee"`
	RealFeeCoinID       int    `json:"real_fee_coin_id"`
	Status              int    `json:"status"`
}

type WithdrawRecordResp struct {
	PageResp
	Records []WithdrawRecordItem `json:"records"`
}

type WithdrawRecordsReq struct {
	CoinID    int `json:"coin_id,optional" form:"coin_id,optional"`
	ChainID   int `json:"chain_id,optional" form:"chain_id,optional"`
	UserID    int `json:"user_id,optional" form:"user_id,optional"`
	StartTime int `json:"start_time,optional" form:"start_time,optional"`
	EndTime   int `json:"end_time,optional" form:"end_time,optional"`
	Page      int `json:"page,optional" form:"page,optional"`
	PageSize  int `json:"page_size,optional" form:"page_size,optional"`
}

type WithdrawRejectReq struct {
	ID     int `json:"id,optional" form:"id,optional"`
	UserID int `json:"user_id,optional" form:"user_id,optional"`
}

type WithdrawRejectResp struct {
	ID int `json:"id"`
}

type WithdrawReq struct {
	Address string `json:"address,optional" form:"address,optional"`
	Memo    string `json:"memo,optional" form:"memo,optional"`
	CoinID  int    `json:"coin_id,optional" form:"coin_id,optional"`
	ChainID int    `json:"chain_id,optional" form:"chain_id,optional"`
	Volume  string `json:"volume,optional" form:"volume,optional"`
	UserID  int    `json:"user_id,optional" form:"user_id,optional"`
}
